In [2]:
import pandas as pd
import matplotlib.pyplot as plt

cpi_All = pd.read_csv('cpi_all_items.csv')
cpi_All['date'] = pd.to_datetime(cpi_All[['year', 'month']].assign(day=1)).dt.to_period('M')
cpi_All.head()

   year  month    cpi     date
0  1999      2  170.6  1999-02
1  1999      4  172.2  1999-04
2  1999      6  172.7  1999-06
3  1999      8  173.4  1999-08
4  1999     10  174.7  1999-10

In [3]:
base = cpi_All[(cpi_All['year'] == 2000) & (cpi_All['month'] == 2)]['cpi'].values[0]
cpi_All['pct_from_2000'] = (cpi_All['cpi'] - base) / base * 100

In [4]:
cpi_All['pct_yoy'] = cpi_All['cpi'].pct_change(periods=6) * 100
cpi_All.head(10)

   year  month    cpi     date  pct_from_2000   pct_yoy
0  1999      2  170.6  1999-02      -3.123225       NaN
1  1999      4  172.2  1999-04      -2.214651       NaN
2  1999      6  172.7  1999-06      -1.930721       NaN
3  1999      8  173.4  1999-08      -1.533220       NaN
4  1999     10  174.7  1999-10      -0.795003       NaN
5  1999     12  174.4  1999-12      -0.965361       NaN
6  2000      2  176.1  2000-02       0.000000  3.223916
7  2000      4  177.8  2000-04       0.965361  3.252033
8  2000      6  179.2  2000-06       1.760363  3.763752
9  2000      8  180.3  2000-08       2.385009  3.979239

In [5]:
cpi_All.to_csv('all_items_cpi_rebased.tsv', sep='\t', index=False)